version: '3'

services:    

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017

    mongo_seed:
        image: mongo
        links:
            - mongo
        volumes:
            - ./mongo-seed:/mongo-seed
        command:
            /mongo-seed/import.sh

    web-app:
        build: .
        ports:
            - 5000:5000
        depends_on:
            - mongo