version: '3'

services:    

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017

    mongo_seed:
        image: mongo
        links:
            - mongo
        volumes:
            - ./services/mongo-seed:/mongo-seed
        command:
            /mongo-seed/import.sh

    web-app:
        build: ./services/web-app/
        command: gunicorn --bind 0.0.0.0:5000 wsgi:application
        volumes:
            - static-volume:/usr/src/app/static
        depends_on:
            - mongo

    nginx:
        image: nginx
        ports:
            - 443:443
            - 80:80
        volumes:
            - ./services/nginx/conf.d:/etc/nginx/conf.d
            - /etc/letsencrypt/:/etc/letsencrypt/
            - static-volume:/usr/src/app/static
        depends_on:
            - web-app

volumes:
    static-volume:
